/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.auth.api;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int buttonSize = 0x7f04006a;
        public static final int circleCrop = 0x7f04009f;
        public static final int colorScheme = 0x7f0400be;
        public static final int imageAspectRatio = 0x7f040168;
        public static final int imageAspectRatioAdjust = 0x7f040169;
        public static final int scopeUris = 0x7f04023b;
    }
    public static final class color {
        private color() {}

        public static final int common_google_signin_btn_text_dark = 0x7f060146;
        public static final int common_google_signin_btn_text_dark_default = 0x7f060147;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f060148;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f060149;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f06014a;
        public static final int common_google_signin_btn_text_light = 0x7f06014b;
        public static final int common_google_signin_btn_text_light_default = 0x7f06014c;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f06014d;
        public static final int common_google_signin_btn_text_light_focused = 0x7f06014e;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f06014f;
        public static final int common_google_signin_btn_tint = 0x7f060150;
    }
    public static final class drawable {
        private drawable() {}

        public static final int common_full_open_on_phone = 0x7f0800c4;
        public static final int common_google_signin_btn_icon_dark = 0x7f0800c5;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f0800c6;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f0800c7;
        public static final int common_google_signin_btn_icon_dark_normal_background = 